name: realestateapi
description: Shelter Plug is an application for real Estate Market.
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.6
  google_fonts: ^4.0.4
  provider: ^6.0.5
  dio: ^5.3.3
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  get: ^4.6.5
  carousel_slider: ^4.2.1
  iconsax: ^0.0.8
  url_launcher: ^6.2.6
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.2.19
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  get_storage: ^2.1.1
  share_plus: ^7.2.1
  firebase_core: ^2.24.2
  readmore: ^2.2.0
  lottie: ^3.0.0
  connectivity_plus: ^5.0.2
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  flutter_paystack: ^1.0.7
  firebase_messaging: ^14.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

 
flutter:

  uses-material-design: true

  
  assets:
    - assets/
    - assets/banners/
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/images/logos/
    - assets/images/animations/
    - assets/images/onboarding/

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
