// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDCWr5IsHXKdh6ie71jrCnEufqjWUYYfY',
    appId: '1:976048600977:web:5ec27ecf4f9245514f4c30',
    messagingSenderId: '976048600977',
    projectId: 'shelterplug-a6c74',
    authDomain: 'shelterplug-a6c74.firebaseapp.com',
    storageBucket: 'shelterplug-a6c74.appspot.com',
    measurementId: 'G-42409ZYHS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9mcVKGv9E5M8bIuF5q0_sgfUSqSfNow',
    appId: '1:976048600977:android:b214c978de59eecc4f4c30',
    messagingSenderId: '976048600977',
    projectId: 'shelterplug-a6c74',
    storageBucket: 'shelterplug-a6c74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmfdX4doMDRrwA3rurBIg7IEKZzmjaYPo',
    appId: '1:976048600977:ios:0b5c51673e7bf7fd4f4c30',
    messagingSenderId: '976048600977',
    projectId: 'shelterplug-a6c74',
    storageBucket: 'shelterplug-a6c74.appspot.com',
    androidClientId: '976048600977-ia926ke0o51debfb8st9pr9qec6gb78m.apps.googleusercontent.com',
    iosClientId: '976048600977-ihh8n91lfo382tcqpqmae9ufmjgmdi7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.realestateapi',
  );
}
